name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SSH config
        run: |
          SSH_CONFIG_PATH="/home/ka522929/.ssh/config"
          echo "Checking for SSH config file: $SSH_CONFIG_PATH"
          ls -l $SSH_CONFIG_PATH
          cat $SSH_CONFIG_PATH
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Set permissions for SSH config
        run: |
          SSH_CONFIG_PATH="/home/ka522929/.ssh/config"
          chmod 600 $SSH_CONFIG_PATH
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Deploy to Server
        run: |
          ssh -T ka522929@${DEPLOY_SERVER} << 'EOF'
          cd /home/ka522929/sisidev.com.ua/www
          git pull origin master
          ./deploy.sh
          EOF
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}