name: Deploy to Server

env:
  WORKDIR: /home/ka522929/sisidev.com.ua/www

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup SSH
        run: |
          apt-get update && apt-get install unzip -y
          apt-get install openssh-client -y
          mkdir -p ~/.ssh
          cat my_known_hosts >> ~/.ssh/known_hosts

      - name: Copy code files on server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} -t "cd ${{ env.WORKDIR }} && git pull"
          echo "Deploy step finished"