name: Deploy to Server

env:
  WORKDIR: /home/ka522929/sisidev.com.ua/www

on:
  push:
    branches:
      - master

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Copy code files on server
        uses: webfactory/ssh-agent@v0.5.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "./*"
          target: ${{ env.WORKDIR }}