name: Deploy to Server

env:
  WORKDIR: /home/ka522929/sisidev.com.ua/www

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Copy code files on server
        run: |
          scp -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }}:${{ env.WORKDIR }}
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} 'bash -s' < deploy.sh
          echo "Deploy step finished"